env:
  RUBY_VERSION: 3.1
  NODE_VERSION: 12
  RAILS_ENV: test
  POSTGRES_PASSWORD: "postgres"

name: Continuous Integration
on: [pull_request]

jobs:
  bundle_install:
    name: Setup Ruby and bundle install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

  yarn_install:
    name: Setup node and yarn install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - run: npm install -g yarn

      - run: yarn install

  tests:
    name: bin/test
    needs: [bundle_install, yarn_install]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Setup database
        run: |
          cp ./.github/workflows/templates/database.yml.github-actions config/database.yml
          bin/rails db:test:prepare

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: Run Tests
        run: bin/test
