env:
  NODE_VERSION: '16'

name: Continuous Integration

on:
  push:
    branches:
      - 'main'  # Set a branch to deploy
  pull_request:

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install node packages
        run: yarn install

      - name: bundle install --with test
        run: bundle install --with test

      - name: Test
        run: bin/bridgetown test

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: bin/bridgetown deploy

      - name: Copy CNAME
        if: github.ref == 'refs/heads/main'
        run: cp ./CNAME ./dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
